In [2]:
import sys, os
import numpy as np
repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)
print("Added to sys.path:", repo_root)
from fixedincomelib import *
print("Fixed Income Library is loaded.")

Added to sys.path: /Users/tiffanyyan/Documents/GitHub/QuantBricks
Fixed Income Library is loaded.

In [2]:
DataConventionRegistry().display_all_data_conventions()

,Name,Type
0,USD-SOFR-OIS,USD-SOFR-OIS
1,USD-FF-3M-OVER-USD-SOFR-OIS-3M,USD-FF-3M-OVER-USD-SOFR-OIS-3M
2,SOFR-FUTURE-3M,SOFR-FUTURE-3M
3,USD-SOFR-SWAPTION,USD-SOFR-SWAPTION
4,USD-SOFR-CAPFLOOR,USD-SOFR-CAPFLOOR
5,USD-SOFR-JUMP,USD-SOFR-JUMP
6,USD-SOFR-IFR,USD-SOFR-IFR
7,USD-FF-IFR,USD-FF-IFR
8,SOFR-1B-FLAT-OVER-SOFR-1B-ZERO-SPREAD,SOFR-1B-FLAT-OVER-SOFR-1B-ZERO-SPREAD
9,FF-1B-FLAT-OVER-FF-1B-ZERO-SPREAD,FF-1B-FLAT-OVER-FF-1B-ZERO-SPREAD
10,USD-GOVT-BOND-FIXED,USD-GOVT-BOND-FIXED
11,EUR-USD,EUR-USD

## Product Bullet Cashflow

In [7]:
# parametric product
termination_date = '2026-05-26'
currency = 'USD'
notional = 1e6
long_or_short = 'LONG'
payment_date = qfAddPeriod(termination_date, '2D', 'F', 'USGS')
prod_bullet_cashflow_1 = qfCreateProductBulletCashflow(
    termination_date,
    currency,
    notional,
    long_or_short
)
prod_bullet_cashflow_2 = qfCreateProductBulletCashflow(
    termination_date,
    currency,
    notional,
    long_or_short,
    payment_date
)

In [8]:
# displayer
display(qfDisplayProduct(prod_bullet_cashflow_1))
display(qfDisplayProduct(prod_bullet_cashflow_2))

               Name                    Value
0      Product Type  PRODUCT_BULLET_CASHFLOW
1          Notional                1000000.0
2          Currency                      USD
3     Long Or Short                     LONG
4  Termination Date               2026-05-26
5      Payment Date               2026-05-26

               Name                    Value
0      Product Type  PRODUCT_BULLET_CASHFLOW
1          Notional                1000000.0
2          Currency                      USD
3     Long Or Short                     LONG
4  Termination Date               2026-05-28
5      Payment Date               2026-05-28

In [9]:
# serialization
# serialize
path = 'product_bullet_cashflow.pickle'
qfWriteProductToFile(prod_bullet_cashflow_1, path)
# deserialize
prod_bullet_cashflow_1_back = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_bullet_cashflow_1_back))
# house keeping
os.remove(path)

               Name                    Value
0      Product Type  PRODUCT_BULLET_CASHFLOW
1          Notional                1000000.0
2          Currency                      USD
3     Long Or Short                     LONG
4  Termination Date               2026-05-26
5      Payment Date               2026-05-26

## Product Fixed Accrued

In [10]:
# parametric product
effecitve_date = '2026-03-26'
termination_date = '2026-05-26'
currency = 'USD'
notional = 1e6
accrual_basis = 'ACT/360'
business_day_convention = 'F'
holiday_convention = 'USGS'
pay_offset = '2D'
payment_date = qfAddPeriod(termination_date, pay_offset, business_day_convention, holiday_convention)
prod_fixed_accrued_1 = qfCreateProducFixedAccrued(
    effecitve_date,
    termination_date,
    currency,
    notional,
    accrual_basis
)
prod_fixed_accrued_2 = qfCreateProducFixedAccrued(
    effecitve_date,
    termination_date,
    currency,
    notional,
    accrual_basis,
    payment_date,
    business_day_convention, 
    holiday_convention
)

In [11]:
# displayer
display(qfDisplayProduct(prod_fixed_accrued_1))
display(qfDisplayProduct(prod_fixed_accrued_2))

                      Name                  Value
0             Product Type  PRODUCT_FIXED_ACCRUED
1                 Notional              1000000.0
2                 Currency                    USD
3            Long Or Short                   LONG
4           Effective Date             2026-03-26
5         Termination Date             2026-05-26
6            Accrual Basis                ACT/360
7             Payment Date             2026-05-26
8  Business Day Convention                      F
9       Holiday Convention                   USGS

                      Name                  Value
0             Product Type  PRODUCT_FIXED_ACCRUED
1                 Notional              1000000.0
2                 Currency                    USD
3            Long Or Short                   LONG
4           Effective Date             2026-03-26
5         Termination Date             2026-05-26
6            Accrual Basis                ACT/360
7             Payment Date             2026-05-28
8  Business Day Convention                      F
9       Holiday Convention                   USGS

In [12]:
# serialization
# serialize
path = 'product_fixed_accrued.pickle'
qfWriteProductToFile(prod_fixed_accrued_2, path)
# deserialize
prod_fixed_accrued_2_back = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(prod_fixed_accrued_2_back))
# house keeping
os.remove(path)

                      Name                  Value
0             Product Type  PRODUCT_FIXED_ACCRUED
1                 Notional              1000000.0
2                 Currency                    USD
3            Long Or Short                   LONG
4           Effective Date             2026-03-26
5         Termination Date             2026-05-26
6            Accrual Basis                ACT/360
7             Payment Date             2026-05-28
8  Business Day Convention                      F
9       Holiday Convention                   USGS

## Product Overnight Index Cashflow

In [13]:
# parametric product
effecitve_date = '2026-03-26'
termination_date = '2027-03-26'
term = '1Y'
overnight_index = 'SOFR-1B'
notional = 1e6
compounding_method = 'compound'
spread = 0.005
business_day_convention = 'F'
holiday_convention = 'USGS'
pay_offset = '2D'
payment_date = qfAddPeriod(termination_date, pay_offset, business_day_convention, holiday_convention)
product_on_cashflow_1 = qfCreateProductOvernightIndexCashflow(
    effecitve_date,
    termination_date,
    overnight_index,
    notional)
product_on_cashflow_2 = qfCreateProductOvernightIndexCashflow(
    effecitve_date,
    term,
    overnight_index,
    notional,
    compounding_method,
    spread,
    payment_date)

In [14]:
# displayer
display(qfDisplayProduct(product_on_cashflow_1))
display(qfDisplayProduct(product_on_cashflow_2))

                 Name                             Value
0        Product Type  PRODUCT_OVERNIGHT_INDEX_CASHFLOW
1            Notional                         1000000.0
2            Currency                               USD
3       Long Or Short                              LONG
4      Effective Date                        2026-03-26
5    Termination Date                        2027-03-26
6            ON Index                 SOFRON Actual/360
7  Compounding Method                          COMPOUND
8              Spread                               0.0
9        Payment Date                        2027-03-26

                 Name                             Value
0        Product Type  PRODUCT_OVERNIGHT_INDEX_CASHFLOW
1            Notional                         1000000.0
2            Currency                               USD
3       Long Or Short                              LONG
4      Effective Date                        2026-03-26
5    Termination Date                        2027-03-29
6            ON Index                 SOFRON Actual/360
7  Compounding Method                          COMPOUND
8              Spread                             0.005
9        Payment Date                        2027-03-30

In [15]:
# serialization
# serialize
path = 'product_on_cashflow.pickle'
qfWriteProductToFile(product_on_cashflow_2, path)
# deserialize
product_on_cashflow_2_back = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(product_on_cashflow_2_back))
# house keeping
os.remove(path)

                 Name                             Value
0        Product Type  PRODUCT_OVERNIGHT_INDEX_CASHFLOW
1            Notional                         1000000.0
2            Currency                               USD
3       Long Or Short                              LONG
4      Effective Date                        2026-03-26
5    Termination Date                        2027-03-29
6            ON Index                 SOFRON Actual/360
7  Compounding Method                          COMPOUND
8              Spread                             0.005
9        Payment Date                        2027-03-30

## Product RFR Future

In [16]:
# parametric product
effecitve_date = '2026-03-26'
termination_date = '2026-06-26'
term = '3M'
future_convention = 'SOFR-FUTURE-3M'
amount = 1e4
strike = 0.
product_on_rfr_future_1 = qfCreateProductRFRFuture(
    effecitve_date,
    termination_date,
    future_convention,
    long_or_short,
    amount,
    strike)
product_on_rfr_future_2 = qfCreateProductRFRFuture(
    effecitve_date,
    termination_date,
    future_convention,
    long_or_short,
    amount,
    strike)

In [17]:
# displayer
display(qfDisplayProduct(product_on_rfr_future_1))
display(qfDisplayProduct(product_on_rfr_future_2))

                Name               Value
0       Product Type  PRODUCT_RFR_FUTURE
1           Notional        2500000000.0
2           Currency                 USD
3      Long Or Short                LONG
4     Effective Date          2026-03-26
5   Termination Date          2026-06-26
6  Future Convention      SOFR-FUTURE-3M
7             Amount             10000.0
8             Strike                 0.0

                Name               Value
0       Product Type  PRODUCT_RFR_FUTURE
1           Notional        2500000000.0
2           Currency                 USD
3      Long Or Short                LONG
4     Effective Date          2026-03-26
5   Termination Date          2026-06-26
6  Future Convention      SOFR-FUTURE-3M
7             Amount             10000.0
8             Strike                 0.0

In [18]:
# serialization
# serialize
path = 'product_rfr_future.pickle'
qfWriteProductToFile(product_on_rfr_future_2, path)
# deserialize
product_on_rfr_future_2_back = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(product_on_rfr_future_2_back))
# house keeping
os.remove(path)

                Name               Value
0       Product Type  PRODUCT_RFR_FUTURE
1           Notional        2500000000.0
2           Currency                 USD
3      Long Or Short                LONG
4     Effective Date          2026-03-26
5   Termination Date          2026-06-26
6  Future Convention      SOFR-FUTURE-3M
7             Amount             10000.0
8             Strike                 0.0

In [19]:
# product factory
value_date = '2025-09-25'
data_convention = 'SOFR-FUTURE-3M'
axis1 = '2025-09-25x2025-12-25'
values = 0.
prod_rfr_from_convention = qfCreateProductFromDataConvention(
    value_date,
    data_convention,
    axis1,
    values)
qfDisplayProduct(prod_rfr_from_convention)

                Name               Value
0       Product Type  PRODUCT_RFR_FUTURE
1           Notional            250000.0
2           Currency                 USD
3      Long Or Short                LONG
4     Effective Date          2025-09-25
5   Termination Date          2025-12-25
6  Future Convention      SOFR-FUTURE-3M
7             Amount                 1.0
8             Strike                 0.0

## Product RFR Swap

In [20]:
effective_date = '2025-05-25'
termination_date = '2027-05-25'
term = '2Y'
pay_offset = '2D'
on_index = 'SOFR-1B'
fixed_rate = 0.04
pay_or_rec = 'pay'
notional = 1e6
accrual_peroid = '1Y'
accrual_basis = 'ACT/360'
floating_leg_accrual_period = '1Y'
business_day_convention = 'F'
holiday_convention = 'USGS'
spread = 0.005
compounding_method = 'compound'
product_on_rfr_swap_1 = qfCreateProductRFRSwap(
    effective_date,
    termination_date,
    pay_offset,
    on_index,
    fixed_rate,
    pay_or_rec,
    notional,
    accrual_peroid,
    accrual_basis)
product_on_rfr_swap_2 = qfCreateProductRFRSwap(
    effective_date,
    term,
    pay_offset,
    on_index,
    fixed_rate,
    pay_or_rec,
    notional,
    accrual_peroid,
    accrual_basis,
    floating_leg_accrual_period,
    business_day_convention,
    holiday_convention,
    spread,
    compounding_method)

In [21]:
# displayer
display(qfDisplayProduct(product_on_rfr_swap_1))
display(qfDisplayProduct(product_on_rfr_swap_2))

                           Name              Value
0                  Product Type   PRODUCT_RFR_SWAP
1                      Notional          1000000.0
2                      Currency                USD
3                 Long Or Short               LONG
4                Effective Date         2025-05-25
5              Termination Date         2027-05-25
6                Payment Offset                 2D
7                      ON Index  SOFRON Actual/360
8                    Fixed Rate               0.04
9                Pay Or Receive                PAY
10               Accrual Period                 1Y
11                Accrual Basis            ACT/360
12  Floating Leg Accrual Period                 1Y
13      Business Day Convention                  F
14           Holiday Convention               USGS
15           Compounding Method           compound

                           Name              Value
0                  Product Type   PRODUCT_RFR_SWAP
1                      Notional          1000000.0
2                      Currency                USD
3                 Long Or Short               LONG
4                Effective Date         2025-05-25
5              Termination Date         2027-05-25
6                Payment Offset                 2D
7                      ON Index  SOFRON Actual/360
8                    Fixed Rate               0.04
9                Pay Or Receive                PAY
10               Accrual Period                 1Y
11                Accrual Basis            ACT/360
12  Floating Leg Accrual Period                 1Y
13      Business Day Convention                  F
14           Holiday Convention               USGS
15           Compounding Method           compound

In [22]:
# examine important member funcions
idx = 0
display(qfDisplayProduct(product_on_rfr_swap_1.floating_leg_cash_flow(idx)))
display(qfDisplayProduct(product_on_rfr_swap_1.fixed_leg_cash_flow(idx)))

                 Name                             Value
0        Product Type  PRODUCT_OVERNIGHT_INDEX_CASHFLOW
1            Notional                         1000000.0
2            Currency                               USD
3       Long Or Short                              LONG
4      Effective Date                        2025-05-25
5    Termination Date                        2026-05-25
6            ON Index                 SOFRON Actual/360
7  Compounding Method                          COMPOUND
8              Spread                               0.0
9        Payment Date                        2026-05-27

                      Name                  Value
0             Product Type  PRODUCT_FIXED_ACCRUED
1                 Notional              1000000.0
2                 Currency                    USD
3            Long Or Short                   LONG
4           Effective Date             2025-05-27
5         Termination Date             2026-05-26
6            Accrual Basis                ACT/360
7             Payment Date             2026-05-28
8  Business Day Convention                      F
9       Holiday Convention                   USGS

In [23]:
# serialization
# serialize
path = 'product_rfr_swap.pickle'
qfWriteProductToFile(product_on_rfr_swap_1, path)
# deserialize
product_on_rfr_swap_1_back = qfReadProductFromFile(path)
# check
display(qfDisplayProduct(product_on_rfr_swap_1_back))
# house keeping
os.remove(path)

                           Name              Value
0                  Product Type   PRODUCT_RFR_SWAP
1                      Notional          1000000.0
2                      Currency                USD
3                 Long Or Short               LONG
4                Effective Date         2025-05-25
5              Termination Date         2027-05-25
6                Payment Offset                 2D
7                      ON Index  SOFRON Actual/360
8                    Fixed Rate               0.04
9                Pay Or Receive                PAY
10               Accrual Period                 1Y
11                Accrual Basis            ACT/360
12  Floating Leg Accrual Period                 1Y
13      Business Day Convention                  F
14           Holiday Convention               USGS
15           Compounding Method           compound

In [24]:
# product factory
value_date = '2025-09-25'
data_convention = 'USD-SOFR-OIS'
axis1 = '5Y'
values = 0.
prod_rfr_swap_from_convention_1 = qfCreateProductFromDataConvention(
    value_date,
    data_convention,
    axis1,
    values)
display(qfDisplayProduct(prod_rfr_swap_from_convention_1))
axis1 = '2025-09-25x2030-09-25'
prod_rfr_swap_from_convention_2 = qfCreateProductFromDataConvention(
    value_date,
    data_convention,
    axis1,
    values)
display(qfDisplayProduct(prod_rfr_swap_from_convention_2))

                           Name              Value
0                  Product Type   PRODUCT_RFR_SWAP
1                      Notional            10000.0
2                      Currency                USD
3                 Long Or Short               LONG
4                Effective Date         2025-09-25
5              Termination Date         2030-09-25
6                Payment Offset                 2D
7                      ON Index  SOFRON Actual/360
8                    Fixed Rate                0.0
9                Pay Or Receive            RECEIVE
10               Accrual Period                 1Y
11                Accrual Basis            ACT/360
12  Floating Leg Accrual Period                 1Y
13      Business Day Convention                  F
14           Holiday Convention               USGS
15           Compounding Method           compound

                           Name              Value
0                  Product Type   PRODUCT_RFR_SWAP
1                      Notional            10000.0
2                      Currency                USD
3                 Long Or Short               LONG
4                Effective Date         2025-09-25
5              Termination Date         2030-09-25
6                Payment Offset                 2D
7                      ON Index  SOFRON Actual/360
8                    Fixed Rate                0.0
9                Pay Or Receive            RECEIVE
10               Accrual Period                 1Y
11                Accrual Basis            ACT/360
12  Floating Leg Accrual Period                 1Y
13      Business Day Convention                  F
14           Holiday Convention               USGS
15           Compounding Method           compound

# Product Bond

In [3]:
# create Bond Specs
x = qfCreateBondSpecs(
    "US9128284W2",
    parameters={
        "ISIN":"US9128284W2",
        "BOND_CONVENTION": "USD-GOVT-BOND-FIXED",
        "ISSUE_DATE": "2026-02-17",
        "FIRST_ACCRUAL_DATE": "2026-02-15",
        "FIRST_COUPON_DATE": "2026-08-15",
        "MATURITY_DATE": "2029-02-15",
        "COUPON_RATE": 0.035,
        "REDEMPTION_PERCENTAGE": 1.0,
    },
)

In [4]:
x.display()

                   Field                Value
0                   NAME          US9128284W2
1                   ISIN          US9128284W2
2        BOND_CONVENTION  USD-GOVT-BOND-FIXED
3             ISSUE_DATE           2026-02-17
4     FIRST_ACCRUAL_DATE           2026-02-15
5      FIRST_COUPON_DATE           2026-08-15
6          MATURITY_DATE           2029-02-15
7            COUPON_RATE                0.035
8  REDEMPTION_PERCENTAGE                  1.0

In [5]:
bond = qfCreateProductBond(
    name="US9128284W2",
    trade_date=Date("2026-02-24"),
    buy_sell="LONG",
)

In [6]:
display(qfDisplayProduct(bond))

                     Name                    Value
0            Product Type             PRODUCT_BOND
1                    ISIN              US9128284W2
2         Bond Convention      USD-GOVT-BOND-FIXED
3              Issue Date               2026-02-17
4      First Accrual Date               2026-02-15
5       First Coupon Date               2026-08-15
6           Maturity Date               2029-02-15
7             Coupon Rate                    0.035
8   Redemption Percentage                      1.0
9              Trade Date               2026-02-24
10        Settlement Date               2026-02-25
11               Buy/Sell                     LONG
12          Num Cashflows                        7
13        Cashflow 0 Type    PRODUCT_FIXED_ACCRUED
14      Cashflow 0 Weight                      1.0
15        Cashflow 1 Type    PRODUCT_FIXED_ACCRUED
16      Cashflow 1 Weight                      1.0
17        Cashflow 2 Type    PRODUCT_FIXED_ACCRUED
18      Cashflow 2 Weight                      1.0
19        Cashflow 3 Type    PRODUCT_FIXED_ACCRUED
20      Cashflow 3 Weight                      1.0
21        Cashflow 4 Type    PRODUCT_FIXED_ACCRUED
22      Cashflow 4 Weight                      1.0
23        Cashflow 5 Type    PRODUCT_FIXED_ACCRUED
24      Cashflow 5 Weight                      1.0
25        Cashflow 6 Type  PRODUCT_BULLET_CASHFLOW
26      Cashflow 6 Weight                      1.0

In [4]:
display(qdDisplaySpecs(x))

                    Name                    Value
0                   ISIN              US9128284W2
1        BOND_CONVENTION  USD-TREASURY-BOND-FIXED
2             ISSUE_DATE               2026-02-17
3     FIRST_ACCRUAL_DATE               2026-02-15
4      FIRST_COUPON_DATE               2026-08-15
5          MATURITY_DATE               2029-02-15
6            COUPON_RATE                    0.035
7  REDEMPTION_PERCENTAGE                      1.0

In [ ]:
bond = qfCreateProductFromDataConvention(
    value_date='2024-01-17',
    data_convention="USD-GOVT-BOND-FIXED"
    axis1='US9128284W34',        
    values=0.035,           
    buy_sell='long',
)

In [5]:
display(qfDisplayProduct(bond))

                     Name                    Value
0            Product Type             PRODUCT_BOND
1                    ISIN             US9128284W34
2         Bond Convention  USD-TREASURY-BOND-FIXED
3              Issue Date               2026-02-17
4      First Accrual Date               2026-02-15
5       First Coupon Date               2026-08-15
6           Maturity Date               2029-02-15
7             Coupon Rate                    0.035
8   Redemption Percentage                      1.0
9         Settlement Date               2024-01-17
10               Buy/Sell                     LONG
11          Num Cashflows                        7
12        Cashflow 0 Type    PRODUCT_FIXED_ACCRUED
13      Cashflow 0 Weight                      1.0
14        Cashflow 1 Type    PRODUCT_FIXED_ACCRUED
15      Cashflow 1 Weight                      1.0
16        Cashflow 2 Type    PRODUCT_FIXED_ACCRUED
17      Cashflow 2 Weight                      1.0
18        Cashflow 3 Type    PRODUCT_FIXED_ACCRUED
19      Cashflow 3 Weight                      1.0
20        Cashflow 4 Type    PRODUCT_FIXED_ACCRUED
21      Cashflow 4 Weight                      1.0
22        Cashflow 5 Type    PRODUCT_FIXED_ACCRUED
23      Cashflow 5 Weight                      1.0
24        Cashflow 6 Type  PRODUCT_BULLET_CASHFLOW
25      Cashflow 6 Weight                      1.0