In [1]:
import sys, os
import numpy as np
repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)
print("Added to sys.path:", repo_root)
from fixedincomelib import *
print("Fixed Income Library is loaded.")

Added to sys.path: c:\QuantBricker
Fixed Income Library is loaded.

### Caplet and Cap

In [2]:
caplet = qfCreateProductRFRCapletFloorlet(
    effective_date="2026-06-17",
    expiry_offset="0D",
    term_or_termination_date="3M",
    payment_date="2026-09-21",
    on_index="SOFR-1B",
    strike=0.045,
    cap_or_floor="CAP",
    notional=1_000_000,
    accrual_basis="ACT/360",
    long_or_short="LONG",
)

In [3]:
qfDisplayProduct(caplet)

                Name                        Value
0       Product Type  PRODUCT_RFR_CAPLET_FLOORLET
1           Notional                      1000000
2           Currency                          USD
3      Long Or Short                         LONG
4     Effective Date                   2026-06-17
5      Expiry Offset                           0D
6        Expiry Date                   2026-06-17
7   Termination Date                   2026-09-17
8       Payment Date                   2026-09-21
9           ON Index            SOFRON Actual/360
10            Strike                        0.045
11      Cap Or Floor                          CAP
12     Accrual Basis                      ACT/360
13           Accrual                     0.255556

In [4]:
cap = qfCreateProductRFRCapFloor(
    effective_date="2026-06-17",
    term_or_termination_date="2Y",
    on_index="SOFR-1B",
    strike=0.045,
    cap_or_floor="CAP",
    notional=1_000_000,
    accrual_period="3M",
    accrual_basis="ACT/360",
    payment_offset="2D",
    payment_business_day_convention="F",
    payment_holiday_convention="USGS",
    long_or_short="LONG",
    business_day_convention="MF",
    holiday_convention="USGS",
)

In [5]:
qfDisplayProduct(cap)

                               Name                  Value
0                      Product Type  PRODUCT_RFR_CAP_FLOOR
1                          Notional                1000000
2                          Currency                    USD
3                     Long Or Short                   LONG
4                    Effective Date             2026-06-17
5                  Termination Date             2028-06-20
6                          ON Index      SOFRON Actual/360
7                            Strike                  0.045
8                      Cap Or Floor                    CAP
9                    Accrual Period                     3M
10                    Accrual Basis                ACT/360
11                   Payment Offset                     2D
12  Payment Business Day Convention                      F
13       Payment Holiday Convention                   USGS
14                      Num Caplets                      9