In [11]:
import sys, os
import numpy as np
import pandas as pd
repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)
print("Added to sys.path:", repo_root)
from fixedincomelib import *
print("Fixed Income Library is loaded.")

Added to sys.path: /Users/nirvana/Documents/NYUQuantClub1
Fixed Income Library is loaded.

## Test Data 1D

In [12]:
df = pd.DataFrame(index=['3M', '6M', '9M', '1Y'])
df['values'] = [.03] * len(df)
data_type = 'Overnight Index Future'
data_conv = 'SOFR-FUTURE-3M'
data1D = qfCreateData1D(data_type, data_conv, df)
display(data1D.display())
# serialize
path = 'data1d.pickle'
qfWriteDataObjectToFile(data1D, path)
# deserialize
data1D_back = qfReadDataObjectFromFile(path)
# check
display(data1D_back.display())
# house keeping
os.remove(path)

  axis1  values
0    3M    0.03
1    6M    0.03
2    9M    0.03
3    1Y    0.03

  axis1  values
0    3M    0.03
1    6M    0.03
2    9M    0.03
3    1Y    0.03

In [13]:
df = pd.DataFrame(index=['3M', '6M', '9M', '1Y'])
df['values'] = [.03] * len(df)
data_type = 'Instantaneous Forward Rate'
data_conv = 'USD-SOFR-IFR'
data1D_ifr = qfCreateData1D(data_type, data_conv, df)
display(data1D_ifr.display())
# serialize
path = 'data1d.pickle'
qfWriteDataObjectToFile(data1D_ifr, path)
# deserialize
data1D_ifr_back = qfReadDataObjectFromFile(path)
# check
display(data1D_ifr_back.display())
# house keeping
os.remove(path)

  axis1  values
0    3M    0.03
1    6M    0.03
2    9M    0.03
3    1Y    0.03

  axis1  values
0    3M    0.03
1    6M    0.03
2    9M    0.03
3    1Y    0.03

## Test Data 2D

In [14]:
df = pd.DataFrame(
    np.random.rand(4, 3),
    index=['3M', '6M', '9M', '1Y'], 
    columns=['1Y', '5Y', '10Y'])
data_type = 'Swaption Normal Volatility'
data_conv = 'USD-SOFR-SWAPTION'
data2D = qfCreateData2D(data_type, data_conv, df)
display(data2D.display())
# serialize
path = 'data2d.pickle'
qfWriteDataObjectToFile(data2D, path)
# deserialize
data2D_back = qfReadDataObjectFromFile(path)
# check
display(data2D_back.display())
# house keeping
os.remove(path)

          1Y        5Y       10Y
3M  0.075229  0.593289  0.752687
6M  0.970590  0.995407  0.138081
9M  0.058268  0.632620  0.040683
1Y  0.713914  0.369728  0.840946

          1Y        5Y       10Y
3M  0.075229  0.593289  0.752687
6M  0.970590  0.995407  0.138081
9M  0.058268  0.632620  0.040683
1Y  0.713914  0.369728  0.840946

## Data Table

In [15]:
df = pd.DataFrame(
    [['2025-01-01', '2025-03-01', 0]]
    , columns=['axis1', 'axis2', 'values'])
data_type = 'JUMP'
data_conv = 'USD-SOFR-JUMP'
data_table = qfCreateDataTable(data_type, data_conv, df)
display(data_table.display())
# serialize
path = 'data_table.pickle'
qfWriteDataObjectToFile(data_table, path)
# deserialize
data_table_back = qfReadDataObjectFromFile(path)
# check
display(data_table_back.display())
# house keeping
os.remove(path)

        axis1       axis2  values
0  2025-01-01  2025-03-01       0

        axis1       axis2  values
0  2025-01-01  2025-03-01       0

## Data Generic

In [21]:
df = pd.DataFrame([['Overnight Index Future', 'SOFR-FUTURE-3M', 'SOFR-1B-FLAT']], columns=['DATA TYPE', 'DATA CONVENTION', 'FUNDING IDENTIFIER'])
data_type = 'DATA GENERIC'
data_label = 'USD-FUNDING-PARAMETERS'
dg = qfCreateDataGeneric(data_type, data_label, df)
display(dg.display())
# serialize
path = 'data_generic.pickle'
qfWriteDataObjectToFile(dg, path)
# deserialize
dg_back = qfReadDataObjectFromFile(path)
# check
display(dg_back.display())
# house keeping
os.remove(path)

                DATA TYPE DATA CONVENTION FUNDING IDENTIFIER
0  Overnight Index Future  SOFR-FUTURE-3M       SOFR-1B-FLAT

                DATA TYPE DATA CONVENTION FUNDING IDENTIFIER
0  Overnight Index Future  SOFR-FUTURE-3M       SOFR-1B-FLAT

## Test Data Collection

In [22]:
### create a data collection
data_list = [data1D, data2D, dg]
data_collection = qfCreateDataCollection(data_list)
display(data_collection.display())

    Data Shape                   Data Type         Data Convention
0       DATA1D      Overnight Index Future          SOFR-FUTURE-3M
1       DATA2D  Swaption Normal Volatility       USD-SOFR-SWAPTION
2  DATAGENERIC                DATA GENERIC  USD-FUNDING-PARAMETERS

In [23]:
### serialization / de-serialization
# serialize
path = 'data_collection.pickle'
qfWriteDataObjectToFile(data_collection, path)
# deserialize
data_collection_back = qfReadDataCollectionFromFile(path)
# check
display(data_collection_back.display())
# house keeping
os.remove(path)

    Data Shape                   Data Type         Data Convention
0       DATA1D      Overnight Index Future          SOFR-FUTURE-3M
1       DATA2D  Swaption Normal Volatility       USD-SOFR-SWAPTION
2  DATAGENERIC                DATA GENERIC  USD-FUNDING-PARAMETERS

In [24]:
### get data from data collection
data_type = 'Overnight Index Future'
data_conv = 'SOFR-FUTURE-3M'
data = data_collection.get_data_from_data_collection(data_type, data_conv)
data.display()

  axis1  values
0    3M    0.03
1    6M    0.03
2    9M    0.03
3    1Y    0.03

In [25]:
### get data generic from data collection
data_type = 'DATA GENERIC'
data_conv = 'USD-FUNDING-PARAMETERS'
data = data_collection.get_data_from_data_collection(data_type, data_conv)
data.display()

                DATA TYPE DATA CONVENTION FUNDING IDENTIFIER
0  Overnight Index Future  SOFR-FUTURE-3M       SOFR-1B-FLAT