In [1]:
import sys, os
repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)
print("Added to sys.path:", repo_root)
from fixedincomelib import *
print("Fixed Income Library is loaded.")

Added to sys.path: c:\QuantBricker
Fixed Income Library is loaded.

## SABR Build Method Collection

In [2]:
### swaption sabr build method
build_method_type = 'IR_SABR'
content = {
    'TARGET' : 'SOFR-1B-SWAPTION',
    'SWAPTION NORMAL VOLATILITY' : 'USD-SOFR-SWAPTION',
    'SWAPTION SABR BETA' : 'USD-SOFR-SWAPTION',
    'SWAPTION SABR NU' : 'USD-SOFR-SWAPTION',
    'SWAPTION SABR RHO' : 'USD-SOFR-SWAPTION',
    'VOL INTERPOLATION DOMAIN' : 'NORMAL VOLATILITY',
    'INTERPOLATION METHOD' : 'LINEAR',
    'EXTRAPOLATION METHOD' : 'FLAT',
    'BUSINESSDAY CONVENTION' : 'F',
    'HOLIDAY CONVENTION' : 'USGS',
    'SHIFT' : 0.04
}
sabr_build_method = qfCreateBuildMethod(build_method_type, content)
display(sabr_build_method.display())

                          Name              Value
0                       TARGET   SOFR-1B-SWAPTION
1   SWAPTION NORMAL VOLATILITY  USD-SOFR-SWAPTION
2           SWAPTION SABR BETA  USD-SOFR-SWAPTION
3             SWAPTION SABR NU  USD-SOFR-SWAPTION
4            SWAPTION SABR RHO  USD-SOFR-SWAPTION
5     VOL INTERPOLATION DOMAIN  NORMAL VOLATILITY
6         INTERPOLATION METHOD             LINEAR
7         EXTRAPOLATION METHOD               FLAT
8       BUSINESSDAY CONVENTION                  F
9           HOLIDAY CONVENTION               USGS
10                       SHIFT               0.04

In [3]:
### serialize / de-serialize
path = 'sabr_build_method.pickle'
qfWriteBuildMethodToFile(sabr_build_method, path)
display(sabr_build_method.display())
sabr_build_method_back = qfReadBuildMethodFromFile(path)
# check
display(sabr_build_method_back.display())
# house keeping
os.remove(path)

                          Name              Value
0                       TARGET   SOFR-1B-SWAPTION
1   SWAPTION NORMAL VOLATILITY  USD-SOFR-SWAPTION
2           SWAPTION SABR BETA  USD-SOFR-SWAPTION
3             SWAPTION SABR NU  USD-SOFR-SWAPTION
4            SWAPTION SABR RHO  USD-SOFR-SWAPTION
5     VOL INTERPOLATION DOMAIN  NORMAL VOLATILITY
6         INTERPOLATION METHOD             LINEAR
7         EXTRAPOLATION METHOD               FLAT
8       BUSINESSDAY CONVENTION                  F
9           HOLIDAY CONVENTION               USGS
10                       SHIFT               0.04

                          Name              Value
0       BUSINESSDAY CONVENTION                  F
1                        SHIFT               0.04
2             SWAPTION SABR NU  USD-SOFR-SWAPTION
3     VOL INTERPOLATION DOMAIN  NORMAL VOLATILITY
4           SWAPTION SABR BETA  USD-SOFR-SWAPTION
5   SWAPTION NORMAL VOLATILITY  USD-SOFR-SWAPTION
6         EXTRAPOLATION METHOD               FLAT
7         INTERPOLATION METHOD             LINEAR
8            SWAPTION SABR RHO  USD-SOFR-SWAPTION
9           HOLIDAY CONVENTION               USGS
10                      TARGET   SOFR-1B-SWAPTION

In [4]:
### caplet
build_method_type = 'IR_SABR'
content_cf = {
    'TARGET' : 'SOFR-1B-CAPFLOOR',
    'SWAPTION NORMAL VOLATILITY' : 'USD-SOFR-CAPFLOOR',
    'SWAPTION SABR BETA' : 'USD-SOFR-CAPFLOOR',
    'SWAPTION SABR NU' : 'USD-SOFR-CAPFLOOR',
    'SWAPTION SABR RHO' : 'USD-SOFR-CAPFLOOR',
    'VOL INTERPOLATION DOMAIN' : 'NORMAL VOLATILITY',
    'INTERPOLATION METHOD' : 'LINEAR',
    'EXTRAPOLATION METHOD' : 'FLAT',
    'BUSINESSDAY CONVENTION' : 'F',
    'HOLIDAY CONVENTION' : 'USGS',
    'SHIFT' : 0.04
}
sabr_build_method_cf = qfCreateBuildMethod(build_method_type, content_cf)
display(sabr_build_method_cf.display())

                          Name              Value
0                       TARGET   SOFR-1B-CAPFLOOR
1   SWAPTION NORMAL VOLATILITY  USD-SOFR-CAPFLOOR
2           SWAPTION SABR BETA  USD-SOFR-CAPFLOOR
3             SWAPTION SABR NU  USD-SOFR-CAPFLOOR
4            SWAPTION SABR RHO  USD-SOFR-CAPFLOOR
5     VOL INTERPOLATION DOMAIN  NORMAL VOLATILITY
6         INTERPOLATION METHOD             LINEAR
7         EXTRAPOLATION METHOD               FLAT
8       BUSINESSDAY CONVENTION                  F
9           HOLIDAY CONVENTION               USGS
10                       SHIFT               0.04

In [5]:
### pack up as build method collection
bm_list = [sabr_build_method, sabr_build_method_cf]
bm_collection = qfCreateModelBuildMethodCollection(bm_list)
bm_collection.display()

      Name             Value
0  IR_SABR  SOFR-1B-SWAPTION
1  IR_SABR  SOFR-1B-CAPFLOOR

## SABR Data Collection

In [6]:
### swaption
expiries = ['3M', '6M', '1Y', '5Y', '10Y']
tenors = ['1Y', '5Y', '10Y']
data_conv = 'USD-SOFR-SWAPTION'
# nv
df = pd.DataFrame(np.random.uniform(low=90./1e4, high=110./1e4, size=(len(expiries), len(tenors))), index=expiries, columns=tenors)
data2D_nv = qfCreateData2D('Swaption Normal Volatility', data_conv, df)
# beta
df = pd.DataFrame(np.random.uniform(low=60./1e2, high=60./1e2, size=(len(expiries), len(tenors))), index=expiries, columns=tenors)
data2D_beta = qfCreateData2D('Swaption SABR Beta', data_conv, df)
# nu
df = pd.DataFrame(np.random.uniform(low=0.01, high=0.3, size=(len(expiries), len(tenors))), index=expiries, columns=tenors)
data2D_nu= qfCreateData2D('Swaption SABR Nu', data_conv, df)
# rho
df = pd.DataFrame(np.random.uniform(low=-0.99, high=0.99, size=(len(expiries), len(tenors))), index=expiries, columns=tenors)
data2D_rho = qfCreateData2D('Swaption SABR Rho', data_conv, df)

In [7]:
### capfloor
expiries = ['3M', '6M', '1Y', '5Y', '10Y']
tenors = ['1Y', '5Y', '10Y']
data_conv = 'USD-SOFR-CAPFLOOR'
# nv
df = pd.DataFrame(np.random.uniform(low=90./1e4, high=110./1e4, size=(len(expiries), len(tenors))), index=expiries, columns=tenors)
data2D_nv_cf = qfCreateData2D('Swaption Normal Volatility', data_conv, df)
# beta
df = pd.DataFrame(np.random.uniform(low=60./1e2, high=60./1e2, size=(len(expiries), len(tenors))), index=expiries, columns=tenors)
data2D_beta_cf = qfCreateData2D('Swaption SABR Beta', data_conv, df)
# nu
df = pd.DataFrame(np.random.uniform(low=0.01, high=0.3, size=(len(expiries), len(tenors))), index=expiries, columns=tenors)
data2D_nu_cf= qfCreateData2D('Swaption SABR Nu', data_conv, df)
# rho
df = pd.DataFrame(np.random.uniform(low=-0.99, high=0.99, size=(len(expiries), len(tenors))), index=expiries, columns=tenors)
data2D_rho_cf = qfCreateData2D('Swaption SABR Rho', data_conv, df)

In [8]:
### create a data collection
data_list = [
    data2D_nv, data2D_beta, data2D_nu, data2D_rho,
    data2D_nv_cf, data2D_beta_cf, data2D_nu_cf, data2D_rho_cf]
data_collection = qfCreateDataCollection(data_list)
display(data_collection.display())

  Data Shape                   Data Type    Data Convention
0     DATA2D  Swaption Normal Volatility  USD-SOFR-SWAPTION
1     DATA2D          Swaption SABR Beta  USD-SOFR-SWAPTION
2     DATA2D            Swaption SABR Nu  USD-SOFR-SWAPTION
3     DATA2D           Swaption SABR Rho  USD-SOFR-SWAPTION
4     DATA2D  Swaption Normal Volatility  USD-SOFR-CAPFLOOR
5     DATA2D          Swaption SABR Beta  USD-SOFR-CAPFLOOR
6     DATA2D            Swaption SABR Nu  USD-SOFR-CAPFLOOR
7     DATA2D           Swaption SABR Rho  USD-SOFR-CAPFLOOR

In [9]:
# ### test creating a sabr component for swaption with swaption build method and its data using SABRModelComponent, which return 4 interpolators for the 4 SABR parameters
# sabr_component = []
# for bm in bm_list:
#     raw_mkt_data = {}
#     if not isinstance(bm, SABRBuildMethod):
#         continue
#     mkt_data_list = []
#     for data_type in bm.calibration_instruments():
#         data_conv = bm[data_type]
#         mkt_data = data_collection.get_data_from_data_collection(data_type, data_conv)
#         raw_mkt_data[data_type] = mkt_data
#         this_axis1 = mkt_data.axis1
#         this_axis2 = mkt_data.axis2
#         this_values = mkt_data.values
#         param = SABRParameters(data_type)
#         mkt_data_list.append((param, this_axis1, this_axis2, this_values))
#     axis1 = mkt_data_list[0][1]
#     axis2 = mkt_data_list[0][2]
#     state_data = {param: values for param, _, _, values in mkt_data_list}
#     market_data = {
#         'AXIS1': axis1,
#         'AXIS2': axis2,
#         'RAW_MKT_DATA': raw_mkt_data
#     }

#     sabr_comp = SABRModelComponent(
#         value_date = Date("2024-06-28"),
#         component_identifier=bm.target_index,
#         state_data=state_data,
#         market_data=market_data,
#         build_method=bm)
#     sabr_component.append(sabr_comp)

# interp = sabr_component[0].interpolator_[SABRParameters.NV]
# interp.interpolate(1.0, 5.0)

In [10]:
# test creating SABR model using SABRModelBuilder
value_date = Date("2024-06-28")

sabr_model = SABRModelBuilder.create_sabr_model_without_yield_curve(
    value_date=value_date,
    data_collection=data_collection,
    build_method_collection=bm_collection
)

In [12]:
caplet = qfCreateProductRFRCapletFloorlet(
    effective_date="2026-06-17",
    expiry_date="2026-06-17",
    term_or_termination_date="3M",
    payment_date="2026-09-21",
    on_index="SOFR-1B",
    strike=0.045,
    cap_or_floor="CAP",
    notional=1_000_000,
    accrual_basis="ACT/360",
    long_or_short="LONG",
)

In [13]:
sabr_model.components_.keys()

dict_keys(['SOFR-1B-SWAPTION', 'SOFR-1B-CAPFLOOR'])

In [17]:
sabr_model.get_sabr_parameters('SOFR-1B-SWAPTION', 1.0, 5.0)

{<SABRParameters.NU: 'SWAPTION SABR NU'>: 0.18511006602824837,
 <SABRParameters.BETA: 'SWAPTION SABR BETA'>: 0.6,
 <SABRParameters.NV: 'SWAPTION NORMAL VOLATILITY'>: 0.010142349435936802,
 <SABRParameters.RHO: 'SWAPTION SABR RHO'>: 0.5750761702205489}

In [15]:
sabr_model.calculate_model_jacobian()

In [ ]:
# pd.DataFrame(sabr_model.model_jacobian).to_clipboard()