In [7]:
import sys, os
repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)
print("Added to sys.path:", repo_root)
from fixedincomelib import *
print("Fixed Income Library is loaded.")

Added to sys.path: /Users/nirvana/Documents/NYUQuantClub1
Fixed Income Library is loaded.

## Test Model Build Method

In [8]:
### create yield curve index build method
build_method_type = 'YIELD_CURVE_INDEX'
content = {
    'TARGET' : 'SOFR-1B',
    'OVERNIGHT INDEX FUTURE' : 'SOFR-FUTURE-3M',
    'OVERNIGHT INDEX SWAP' : 'USD-SOFR-OIS',
    'INSTANTANEOUS FORWARD RATE' : 'USD-SOFR-IFR'
}
yc_build_method = qfCreateBuildMethod(build_method_type, content)
display(yc_build_method.display())

                          Name                               Value
0                       TARGET                             SOFR-1B
1       OVERNIGHT INDEX FUTURE                      SOFR-FUTURE-3M
2         OVERNIGHT INDEX SWAP                        USD-SOFR-OIS
3   INSTANTANEOUS FORWARD RATE                        USD-SOFR-IFR
4                         SWAP
5                 LIBOR FUTURE
6         EXTRAPOLATION METHOD                                FLAT
7         INTERPOLATION METHOD  PIECEWISE_CONSTANT_LEFT_CONTINUOUS
8              REFERENCE INDEX
9                       FIXING
10  OVERNIGHT INDEX BASIS SWAP

In [9]:
### serialize / de-serialize
path = 'yc_build_method.pickle'
qfWriteBuildMethodToFile(yc_build_method, path)
display(yc_build_method.display())
yc_build_method_back = qfReadBuildMethodFromFile(path)
# check
display(yc_build_method_back.display())
# house keeping
os.remove(path)

                          Name                               Value
0                       TARGET                             SOFR-1B
1       OVERNIGHT INDEX FUTURE                      SOFR-FUTURE-3M
2         OVERNIGHT INDEX SWAP                        USD-SOFR-OIS
3   INSTANTANEOUS FORWARD RATE                        USD-SOFR-IFR
4                         SWAP
5                 LIBOR FUTURE
6         EXTRAPOLATION METHOD                                FLAT
7         INTERPOLATION METHOD  PIECEWISE_CONSTANT_LEFT_CONTINUOUS
8              REFERENCE INDEX
9                       FIXING
10  OVERNIGHT INDEX BASIS SWAP

                          Name                               Value
0   INSTANTANEOUS FORWARD RATE                        USD-SOFR-IFR
1                         SWAP
2                 LIBOR FUTURE
3         EXTRAPOLATION METHOD                                FLAT
4         INTERPOLATION METHOD  PIECEWISE_CONSTANT_LEFT_CONTINUOUS
5       OVERNIGHT INDEX FUTURE                      SOFR-FUTURE-3M
6              REFERENCE INDEX
7                       FIXING
8         OVERNIGHT INDEX SWAP                        USD-SOFR-OIS
9   OVERNIGHT INDEX BASIS SWAP
10                      TARGET                             SOFR-1B

In [10]:
### create yield curve fx build method
build_method_type = 'YIELD_CURVE_FX'
content = {
    'TARGET' : 'EUR-USD',
    'FX SPOT RATE' : 'EUR-USD'
}
yc_build_method_fx = qfCreateBuildMethod(build_method_type, content)
display(yc_build_method_fx.display())

           Name    Value
0        TARGET  EUR-USD
1  FX SPOT RATE  EUR-USD

In [11]:
### serialize / de-serialize
path = 'yc_build_method_fx.pickle'
qfWriteBuildMethodToFile(yc_build_method_fx, path)
display(yc_build_method_fx.display())
yc_build_method_fx_back = qfReadBuildMethodFromFile(path)
# check
display(yc_build_method_fx_back.display())
# house keeping
os.remove(path)

           Name    Value
0        TARGET  EUR-USD
1  FX SPOT RATE  EUR-USD

           Name    Value
0  FX SPOT RATE  EUR-USD
1        TARGET  EUR-USD

In [12]:
### create yield curve common build method 
build_method_type = 'YIELD_CURVE_COMMON'
content = {
    'TARGET' : 'USD',
    'FUNDING PARAMETERS' : 'USD-FUNDING-PARAMETERS',
    'SOLVER' : 'BRENT'}
yc_common_build_method = qfCreateBuildMethod(build_method_type, content)
display(yc_common_build_method.display())
### serialize / de-serialize
path = 'yc_build_method_common.pickle'
qfWriteBuildMethodToFile(yc_common_build_method, path)
yc_common_build_method_back = qfReadBuildMethodFromFile(path)
# check
display(yc_common_build_method_back.display())
# house keeping
os.remove(path)

                 Name                   Value
0              TARGET                     USD
1  FUNDING PARAMETERS  USD-FUNDING-PARAMETERS
2              SOLVER                   BRENT

                 Name                   Value
0              SOLVER                   BRENT
1  FUNDING PARAMETERS  USD-FUNDING-PARAMETERS
2              TARGET                     USD

## Test Build Method Collection

In [13]:
### create a data collection
bm_list = [yc_build_method, yc_build_method_fx, yc_common_build_method]
bm_collection = qfCreateModelBuildMethodCollection(bm_list)
display(bm_collection.display())

                 Name    Value
0   YIELD_CURVE_INDEX  SOFR-1B
1      YIELD_CURVE_FX  EUR-USD
2  YIELD_CURVE_COMMON      USD

In [14]:
### serialization / de-serialization
# serialize
path = 'build_method_collection.pickle'
qfWriteBuildMethodCollectionToFile(bm_collection, path)
# deserialize
build_method_collecion_back = qfReadBuildMethodCollectionFromFile(path)
# check
display(build_method_collecion_back.display())
# house keeping
os.remove(path)

                 Name    Value
0   YIELD_CURVE_INDEX  SOFR-1B
1      YIELD_CURVE_FX  EUR-USD
2  YIELD_CURVE_COMMON      USD