In [10]:
import sys, os
repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)
print("Added to sys.path:", repo_root)
from fixedincomelib import *
print("Fixed Income Library is loaded.")

Added to sys.path: /Users/nirvana/Documents/NYUQuantClub1
Fixed Income Library is loaded.

## Test Data Conevntions

In [11]:
### load data conventions from files
qfListAllDataConventions()

,Name,Type
0,USD-SOFR-OIS,USD-SOFR-OIS
1,USD-FF-3M-OVER-USD-SOFR-OIS-3M,USD-FF-3M-OVER-USD-SOFR-OIS-3M
2,SOFR-FUTURE-3M,SOFR-FUTURE-3M
3,USD-SOFR-SWAPTION,USD-SOFR-SWAPTION
4,USD-SOFR-CAPFLOOR,USD-SOFR-CAPFLOOR
5,USD-SOFR-JUMP,USD-SOFR-JUMP
6,USD-SOFR-IFR,USD-SOFR-IFR
7,USD-FF-IFR,USD-FF-IFR
8,SOFR-1B-FLAT-OVER-SOFR-1B-ZERO-SPREAD,SOFR-1B-FLAT-OVER-SOFR-1B-ZERO-SPREAD
9,FF-1B-FLAT-OVER-FF-1B-ZERO-SPREAD,FF-1B-FLAT-OVER-FF-1B-ZERO-SPREAD
10,EUR-USD,EUR-USD
11,GBP-OIS,GBP-OIS

In [12]:
### clear data convention
# clear a specific convention
qfReloadDataConventions() # load all for test below
qfClearDataConventionRegistry('SOFR-FUTURE-3M')
display(qfListAllDataConventions())
# clear all conventions
qfClearDataConventionRegistry('*')
display(qfListAllDataConventions())
print('Data Convention Registry is now empty.')
qfReloadDataConventions() # load all for test below

Data convention is reloaded from file.

,Name,Type
0,USD-SOFR-OIS,USD-SOFR-OIS
1,USD-FF-3M-OVER-USD-SOFR-OIS-3M,USD-FF-3M-OVER-USD-SOFR-OIS-3M
2,USD-SOFR-SWAPTION,USD-SOFR-SWAPTION
3,USD-SOFR-CAPFLOOR,USD-SOFR-CAPFLOOR
4,USD-SOFR-JUMP,USD-SOFR-JUMP
5,USD-SOFR-IFR,USD-SOFR-IFR
6,USD-FF-IFR,USD-FF-IFR
7,SOFR-1B-FLAT-OVER-SOFR-1B-ZERO-SPREAD,SOFR-1B-FLAT-OVER-SOFR-1B-ZERO-SPREAD
8,FF-1B-FLAT-OVER-FF-1B-ZERO-SPREAD,FF-1B-FLAT-OVER-FF-1B-ZERO-SPREAD
9,EUR-USD,EUR-USD

Empty DataFrame
Columns: [Name, Type]
Index: []

Data Convention Registry is now empty.
Data convention is reloaded from file.

In [13]:
### register new convention
# test insert a gbp ois swap
name = 'GBP-OIS'
type = 'RFR SWAP'
content = {
    "index": "SONIA-1B",
    "accrual_basis": "ACT/365",
    "accrual_period": "1Y",
    "payment_offset": "2B",
    "payment_business_day_convention": "MF",
    "payment_holiday_convention": "LON",
    "compounding_method": "COMPOUND"
}
qfRegisterDataConvention(name, type, content)
qfDisplayDataConvention(name)
qfListAllDataConventions()

GBP-OIS is registered.

,Name,Type
0,USD-SOFR-OIS,USD-SOFR-OIS
1,USD-FF-3M-OVER-USD-SOFR-OIS-3M,USD-FF-3M-OVER-USD-SOFR-OIS-3M
2,SOFR-FUTURE-3M,SOFR-FUTURE-3M
3,USD-SOFR-SWAPTION,USD-SOFR-SWAPTION
4,USD-SOFR-CAPFLOOR,USD-SOFR-CAPFLOOR
5,USD-SOFR-JUMP,USD-SOFR-JUMP
6,USD-SOFR-IFR,USD-SOFR-IFR
7,USD-FF-IFR,USD-FF-IFR
8,SOFR-1B-FLAT-OVER-SOFR-1B-ZERO-SPREAD,SOFR-1B-FLAT-OVER-SOFR-1B-ZERO-SPREAD
9,FF-1B-FLAT-OVER-FF-1B-ZERO-SPREAD,FF-1B-FLAT-OVER-FF-1B-ZERO-SPREAD
10,EUR-USD,EUR-USD
11,GBP-OIS,GBP-OIS

## Test Index

In [14]:
### load index from files
qfListAllIndex()

                Name                  QuantLibIndex
0   USD-LIBOR-BBA-3M          USDLibor3M Actual/360
1            SOFR-1B              SOFRON Actual/360
2              FF-1B          FedFundsON Actual/360
3   GBP-LIBOR-BBA-3M  GBPLibor3M Actual/365 (Fixed)
4           SONIA-1B     SoniaON Actual/365 (Fixed)
5    CAD-LIBOR-BA-3M  CADLibor3M Actual/365 (Fixed)
6           CORRA-1B     CORRAON Actual/365 (Fixed)
7         EURIBOR-6M           Euribor6M Actual/360
8              EONIA             EoniaON Actual/360
9   AUD-LIBOR-BBA-3M          AUDLibor3M Actual/360
10          AONIA-1B     AoniaON Actual/365 (Fixed)
11  JPY-LIBOR-BBA-3M          JPYLibor3M Actual/360
12          TONIA-1B     TonarON Actual/365 (Fixed)
13           EUR-USD                        EUR-USD

In [15]:
IndexRegistry().get('EUR-USD').display() # LIKE IT!

                       Name   Value
0                  BASE_CCY     EUR
1    BASE_BUSINESS_DAY_CONV       F
2             BASE_HOLIDAYS  TARGET
3        BASE_FIXING_OFFSET      2D
4                QUOTED_CCY     USD
5  QUOTED_BUSINESS_DAY_CONV       F
6           QUOTED_HOLIDAYS     NYC
7      QUOTED_FIXING_OFFSET      0D
8               PREMIUM_CCY     USD

In [16]:
### clear index 
# clear a specific convention
qfReloadIndex() # load all for test below
qfClearIndexRegistry('AUD-LIBOR-BBA-3M')
display(qfListAllIndex())
# clear all indices
qfClearIndexRegistry('*')
display(qfListAllIndex())
print('Index Registry is now empty.')
qfReloadIndex() # load all for test below

Indices is reloaded from file.

                Name                  QuantLibIndex
0   USD-LIBOR-BBA-3M          USDLibor3M Actual/360
1            SOFR-1B              SOFRON Actual/360
2              FF-1B          FedFundsON Actual/360
3   GBP-LIBOR-BBA-3M  GBPLibor3M Actual/365 (Fixed)
4           SONIA-1B     SoniaON Actual/365 (Fixed)
5    CAD-LIBOR-BA-3M  CADLibor3M Actual/365 (Fixed)
6           CORRA-1B     CORRAON Actual/365 (Fixed)
7         EURIBOR-6M           Euribor6M Actual/360
8              EONIA             EoniaON Actual/360
9           AONIA-1B     AoniaON Actual/365 (Fixed)
10  JPY-LIBOR-BBA-3M          JPYLibor3M Actual/360
11          TONIA-1B     TonarON Actual/365 (Fixed)
12           EUR-USD                        EUR-USD

Empty DataFrame
Columns: [Name, QuantLibIndex]
Index: []

Index Registry is now empty.
Indices is reloaded from file.

In [18]:
### register a new index
name = 'FedFunds'
qfRegisterIndex('USD-FEDFUND', {'type' : 'native', 'index' : name})
qfListAllIndex()

USD-FEDFUND is registered.

                Name                  QuantLibIndex
0   USD-LIBOR-BBA-3M          USDLibor3M Actual/360
1            SOFR-1B              SOFRON Actual/360
2              FF-1B          FedFundsON Actual/360
3   GBP-LIBOR-BBA-3M  GBPLibor3M Actual/365 (Fixed)
4           SONIA-1B     SoniaON Actual/365 (Fixed)
5    CAD-LIBOR-BA-3M  CADLibor3M Actual/365 (Fixed)
6           CORRA-1B     CORRAON Actual/365 (Fixed)
7         EURIBOR-6M           Euribor6M Actual/360
8              EONIA             EoniaON Actual/360
9   AUD-LIBOR-BBA-3M          AUDLibor3M Actual/360
10          AONIA-1B     AoniaON Actual/365 (Fixed)
11  JPY-LIBOR-BBA-3M          JPYLibor3M Actual/360
12          TONIA-1B     TonarON Actual/365 (Fixed)
13           EUR-USD                        EUR-USD
14       USD-FEDFUND          FedFundsON Actual/360

## Test Index Fixings

In [19]:
### list index fixings
index_name = 'USD-LIBOR-BBA-3M'
qfListIndexFixings(index_name.lower())

Empty DataFrame
Columns: [Date, Fixing]
Index: []

In [20]:
### list index fixings for a specific start date and end date
index_name = 'USD-LIBOR-BBA-3M'
qfReloadIndexFixings() # load all back for testing below
qfListIndexFixings(
    index_name,
    start_date='2025-06-17',
    end_date='2025-06-18'
)

All fxings are reloaded from file.

         Date   Fixing
0  2025-06-17  0.02730
1  2025-06-18  0.02735

In [ ]:
### insert index fixings
qfInsertIndexFixing(index_name, '2026-06-19', 0.02736)
display(qfListIndexFixings(index_name))
# insert more
dates = ['2026-06-20', '2026-06-21']
fixings = [0.02, 0.02]
qfInsertIndexFixing(index_name, dates, fixings)
display(qfListIndexFixings(index_name))
# remove index fixings
qfRemoveIndexFixings(index_name, dates)
display(qfListIndexFixings(index_name))

1 fixing(s) for USD-LIBOR-BBA-3M is(are) inserted.

         Date   Fixing
0  2025-06-16  0.02725
1  2025-06-17  0.02730
2  2025-06-18  0.02735
3  2026-06-19  0.02736

2 fixing(s) for USD-LIBOR-BBA-3M is(are) inserted.

         Date   Fixing
0  2025-06-16  0.02725
1  2025-06-17  0.02730
2  2025-06-18  0.02735
3  2026-06-19  0.02736
4  2026-06-20  0.02000
5  2026-06-21  0.02000

2 fixings of USD-LIBOR-BBA-3M are moved.

         Date   Fixing
0  2025-06-16  0.02725
1  2025-06-17  0.02730
2  2025-06-18  0.02735
3  2026-06-19  0.02736

In [ ]:
### remove all fixings
# remove all index fixings
qfRemoveIndexFixings('*')
qfListAllIndexFixings()

Empty DataFrame
Columns: [Index]
Index: []

In [ ]:
### remove a specific fixing
name = 'USD-LIBOR-BBA-3M'
qfReloadIndexFixings() # load all back for testing below
qfRemoveIndexFixings(name)
qfListAllIndexFixings(name)
qfListAllIndexFixings('*')

All fxings are reloaded from file.
The fixings of USD-LIBOR-BBA-3M are all removed.

      Index
0   SOFR-1B
1  SONIA-1B